### ISSUE TITLE
Test endpoint

### ISSUE THREAD

**Issue by mediafreakch** [johnpduane/confluence-api#1]
Hello,

Many thanks for sharing this module! A question related to the tests you wrote: 
https://confluence-api-test.atlassian.net/wiki is it a public test-server or your own, that you pay for?

Edi

**Comment by johnpduane** [comment]
Hi Edi,

Yes, the confluence instance used in the tests is public.  When I initially set up the tests, Atlassian was offering a free tier.  I suppose Atlassian may want to start charging me for the instance and if so, I will likely let it lapse.  The instance still seems to be working so feel free to exercise the API using it if you'd like.  

Also, if you have any suggestions for this module, I'd love your input.  Thanks!

**Comment by mediafreakch** [comment]
Alright, thanks for the info!
