### ISSUE TITLE
Not able to put the content in an existing page in a space.

### ISSUE THREAD

**Issue by csaicharan** [johnpduane/confluence-api#14]
Hi,

I am facing an issue, i am not able to update the content of available page in confluence. This is my sample request.

    confluence.putContent(<space_id>,<page_id>,<current_versionId>, 'Test Page', '<h1>Updated</h1>', function (err, response) {
        if (!err) {
            console.log('Done');
        } else {
            console.log(err.message);
        }
    }, true);

When i run this, i am getting "Conflict" as an error response.

I tried to increment the version ID of the to the same page, but i am returning with "BAD REQUEST" as an error response.

**Comment by johnpduane** [comment]
Hi @saicharan-etp - Sorry for the delay responding and hope you found a fix already. If not, I hope the following helps.

From the [Confluence REST documentation for updating content](https://developer.atlassian.com/cloud/confluence/rest/#api-content-id-put), here is a description of the two error responses you are seeing:

> **400 Bad Request**
Returned if;
The request body is missing required parameters (version, type, title).
The type property has been set incorrectly.

> **409 Conflict**
Returned if; - The page is a draft (draft pages cannot be updated). - The version property has not been set correctly for the content type.

So, I would first check to see if the page is a 'draft' and if not, then you may not be incrementing the version number correctly. Hope this helps!!
