### ISSUE TITLE
Not able to put correctly (likely user error)

### ISSUE THREAD

**Issue by waltermvp** [johnpduane/confluence-api#17]
First off great repo thank you!!!

 I have `getContentByID` working however im struggling to get `putContent` to work. Im fairly sure the issue lies in the sting passed to the `content` parameter. 

```node
  confluence.putContent(
    "AI",
    "1234567",
    "2",
    "Name of document",
    '"body":{"storage":{"value":"<p>This is the updated text for the new page</p>","representation":"storage"}',
    (err, data) => {
      console.log("Started");
      if (err) {
        callback(null, { statusCode: 405, body: JSON.stringify(err) });
      } else {
        console.log(data);
        callback(null, { statusCode: 200, body: JSON.stringify(data) });
      }
    }
  );
```

Is my `content` sting malformed?

**Comment by waltermvp** [comment]
Also i wouldnt mind submitting a pr  with some examples for `putContent` in the README

**Comment by waltermvp** [comment]
@johnpduane shamelessly reaching out :)

**Comment by johnpduane** [comment]
Hello @waltermvp - Sorry for the delay responding. 

Yes, the issue could be the content parameter. The `putContent` function handles placing the HTML you want to PUT within `body.storage.value`, see [confluence.js#L232-L261](https://github.com/johnpduane/confluence-api/blob/master/lib/confluence.js#L232-L261).  So, in your example, that argument could just be `'<p>This is the updated text for the new page</p>'`

Two other things that may be useful:
1. The `version` argument should be a number and needs to be incremented with each call to putContent. I think the backend API will generate an error if the version supplied is already in the page's history.
2. There are decent examples in the unit tests, so take a peek at https://github.com/johnpduane/confluence-api/blob/master/test/api-test.js#L176-L199

Hope this helps!

**Comment by waltermvp** [comment]
@johnpduane precisely what i need, very thankful for the response i'll close this ticket now. Once again thanks for your great work

**Comment by waltermvp** [comment]
Apologies for the bother. Unfortunately i'm still getting a 405 error.

Here is the node code 

```node 
  confluence.putContent(
    "AI",
    "577372170",
    3,
    "TC Upload Process",
    "<p>This is the updated text for the new page</p>",
    (err, data) => {
      console.log("Started");
      if (err) {
        console.log(data);
        console.log("217");
        console.log(JSON.stringify(err));
        console.log("221");
        callback(null, { statusCode: 187, body: JSON.stringify(err) });
      } else {
        console.log(data);
        callback(null, { statusCode: 200, body: JSON.stringify(data) });
      }
    },
    null,
    null
  );
```

here is the error response.

```json
{"original":null,"response":{"req":{"method":"PUT","url":"https://xxxxx.atlassian.net/wiki/rest/prototype/latest/content/577372170.json?expand=body.storage,version","data":{"id":"577372170","type":"page","title":"TC Upload Process","space":{"key":"AI"},"version":{"number":3,"minorEdit":false},"body":{"storage":{"value":"<p>This is the updated text for the new page</p>","representation":"storage"}}}},"header":{"server":"Atlassian Proxy/0.1.281","content-type":"text/plain","strict-transport-security":"max-age=315360000; includeSubDomains; preload","date":"Wed, 18 Jul 2018 17:43:43 GMT","x-xss-protection":"1; mode=block","x-ausername":"username","x-content-type-options":"nosniff","connection":"close","allow":"HEAD,GET,OPTIONS","content-length":"0"},"status":405,"text":""},"status":405}
```

Any clue what's going on here? @johnpduane 

Im using the `getContentById` successfully  and here is the current version info
![screen shot 2018-07-18 at 1 49 23 pm](https://user-images.githubusercontent.com/1158238/42898547-73b05be8-8a91-11e8-83e9-f7f24421d9c8.png)

**Comment by triusis92** [comment]
Hi, when trying to update a page, the putContent method instead deletes all the content and just leaves the title of the page. The call is below:

`confluence.putContent("testSpace","pageID",versionNo, "Test Page Title", updatedContent, function(err, data) {
      console.log(data);
  });`

Below is the updatedContent that I'm trying to put in the body of confluence page.

`<div class="table-wrap"><div class="table-wrap"><p class="auto-cursor-target"><br /></p><table class="relative-table wrapped tablesorter tablesorter-default stickyTableHeaders" style="width: 51.9417%;"><colgroup><col style="width: 8.90625%;" /><col style="width: 91.0938%;" /><col /></colgroup><tbody><tr class="tablesorter-headerRow"><th class="tablesorter-header sortableHeader tablesorter-headerUnSorted" style="text-align: left;" scope="col"><div class="tablesorter-header-inner">Timestamp</div></th><th class="tablesorter-header sortableHeader tablesorter-headerUnSorted" style="text-align: left;" scope="col"><div class="tablesorter-header-inner">Component</div></th><th class="tablesorter-header sortableHeader tablesorter-headerUnSorted" colspan="1">Status</th></tr><tr><td style="text-align: left;">15:43</td><td style="text-align: left;"><span>Ops &amp; CS reporting that reports are viewable</span></td><td colspan="1"><br /></td></tr><tr><td style="text-align: left;" colspan="1"><br /></td><td style="text-align: left;" colspan="1"><br /></td><td colspan="1"><br /></td></tr><tr><td style="text-align: left;">Test timestamp</td><td style="text-align: left;"><span>Test component</span></td><td colspan="1"><br /></td></tr></tbody></table><p class="auto-cursor-target"><br /></p></div></div>`

I am not getting any errors, if need be I can post the response I get from that call.
Thanks
