### ISSUE TITLE
Custom Expanders

### ISSUE THREAD

**Issue by lukouko** [johnpduane/confluence-api#2]
I need to be able to provide custom expanders to getContentById. I can see in the current code that expand fields default to body.storage,version.

Two possible options;
- Change getContentById to process variable number of arguments. Second optional argument would be expanders which is basically an array of expanded fields. Acceptable signatures would be:
  getContentById(id, cb) or getContentById(id, expanders, cb). In the former case, the current default expansions would be used. In the latter case, expanders would override default.
- Add a new function: getExpandedContentById(id, expanders, cb)

Please let me which is preferred, happy to branch and provide pull request.

**Comment by johnpduane** [comment]
Sorry for the long delay getting back to you!!

If you are still interested in making this change, either option works for me. It would be great if you could update or add a test too. If you send me a pull request I promise to look at it right away. :-)

Thanks!
